
public.swagger_ui:
    path: /public/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }

collective.swagger_ui:
    path: /collective/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: collective }
