
public.json:
    path: /public/browse/{groupName}.json
    controller: "App\\Controller\\PublicSide\\BrowseController::browseJsonAction"
    methods: ['GET']

public.html:
    path: /public/browse/{groupName}.html
    controller: "App\\Controller\\PublicSide\\BrowseController::browseRenderedAction"
    methods: ['GET']

public.main_page:
    path: /
    controller: "App\\Controller\\PublicSide\\IndexController::indexAction"
    methods: ['GET']
